name: On Push (Master)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/pr.yml

  docker-publish:
    name: Build Docker Image & Publish
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to My Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.MY_REGISTRY }}
          username: ${{ secrets.MY_REGISTRY_USERNAME }}
          password: ${{ secrets.MY_REGISTRY_PASSWORD }}

      - name: Get Version From package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build & Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          GHCR_IMAGE: ghcr.io/${{ github.repository }}
          MY_REGISTRY_IMAGE: ${{ secrets.MY_REGISTRY }}/public/${{ github.event.repository.name }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:latest
            ${{ env.GHCR_IMAGE }}:${{ steps.package-version.outputs.current-version }}
            ${{ env.MY_REGISTRY_IMAGE }}:latest
            ${{ env.MY_REGISTRY_IMAGE }}:${{ steps.package-version.outputs.current-version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            DATE_CREATED=${{ steps.date.outputs.date }}
            VERSION=${{ steps.package-version.outputs.current-version }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
